# Generated by Django 4.2.4 on 2023-09-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_doc_eudcation_doctor_doc_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='admin',
        ),
    ]
