# Generated by Django 4.2.4 on 2023-09-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_user_doctor_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_specialist',
            field=models.CharField(default='', max_length=50),
        ),
    ]
