# Generated by Django 4.2.4 on 2023-09-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_doctor_doc_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_education',
            field=models.CharField(default='', max_length=50),
        ),
    ]
