# Generated by Django 4.2.4 on 2023-09-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_doctor_doc_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_education',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doc_specialist',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
