# Generated by Django 4.2.4 on 2023-09-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_doctor_doc_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Doctor'), ('2', 'Patient')], default=2, max_length=20),
        ),
    ]
