# Generated by Django 4.2.4 on 2023-09-23 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_doctor_doc_education_and_more'),
        ('booking', '0002_alter_appointment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appoiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.doctor'),
        ),
    ]
